[workspace]
resolver = "3"
members = ["bacarrat", "bazaar", "card", "house"]


[workspace.dependencies]
rand = "=0.10.0-rc.8"
rand_core = "=0.10.0"
rand_chacha = "0.10.0-rc.6"
chacha20 = "=0.10.0-rc.8"