[package]
name = "card"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
rand_chacha = "*"

[dependencies]
thiserror = "*"
rand = "*"
common_errors = { git = "https://github.com/Tokeiya/common_errors", branch = "master" }